### PR TITLE
BREAKING CHANGE replaced phpexcel and change minimum php version to 7.2

### PR DESCRIPTION
**Pull request by hoffigk**

### CODE REVIEW

**Comment by hoffigk** [comment]
ping @DracoBlue any chance to get this merged? :)

**Comment by DracoBlue** [comment]
Sorry for missing this :(

**Comment by DracoBlue** [comment]
Can you add changelog for 3.1.0 and add this change?

Then I will merge and tag the release.

**Comment by hoffigk** [comment]
After updating my branch, i noticed that the change to PHP 7.2 and phpoffice have already been made. So I will close this PR.

**Pull request closed without merging**
