### PR TITLE
Adds php8.x support

### LINKED ISSUE #42: PHP 8 support
Is PHP8 support planned?

### PR DESCRIPTION
**Pull request by mvhirsch**
Tests pass on php8.1 (it works on my machine :joy:)

Let's see if travis tells same.

Closes #42

### CODE REVIEW

**Comment by mvhirsch** [comment]
@DracoBlue I can't find any build server. Is there no CI?

**Comment by DracoBlue** [comment]
Travis seems to be shut down :(.


Can you also add github actions plz! :)

**Comment by DracoBlue** [comment]
Tests and commands are here

https://github.com/DracoBlue/Craur/blob/master/.travis.yml

**Comment by DracoBlue** [comment]
Fixed with https://github.com/DracoBlue/Craur/pull/45

**Pull request closed without merging**
